DEFAULT_TEXT_FONT_COLOR = "White"
DEFAULT_TEXT_OUTLINE_FONT_COLOR = "Black"
DEFAULT_TEXT_FONT_SIZE = 25
DEFAULT_TEXT_FONT_PATH = None

DEFAULT_CASE_SIZE = 50
DEFAULT_CASE_TYPE = "Case"
DEFAULT_CASE_COLOR = "White"